--- #YAML:1.0
name:               SVG
version:            2.49
abstract:           Perl extension for generating Scalable Vector Graphics (SVG) documents
author:
    - Ronan Oger <ronan@cpan.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
