--- #YAML:1.0
name:                SVG
version:             2.39
abstract:            Perl extension for generating Scalable Vector Graphics (SVG) documents
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Ronan Oger <ronan@cpan.com>
